name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Build
        run: npm run build

      - name: Config git-user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.mail "<>"

      - name: Commit and push
        run: |
          git add docs
          git commit -m ":rocket: automatic build"
          git push
